CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest IS 
BEGIN 
  UPDATE ACCOUNTS 
  SET BALANCE = BALANCE + (BALANCE * 0.01) 
  WHERE UPPER(ACCOUNTTYPE) = 'SAVINGS'; 
 
  COMMIT; 
END; 


BEGIN 
  ProcessMonthlyInterest; 
END;



SELECT * FROM ACCOUNTS